require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe DiplomasController do

  def mock_diploma(stubs={})
    @mock_diploma ||= mock_model(Diploma, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all diplomas as @diplomas" do
      Diploma.stub(:all) { [mock_diploma] }
      get :index
      assigns(:diplomas).should eq([mock_diploma])
    end
  end

  describe "GET show" do
    it "assigns the requested diploma as @diploma" do
      Diploma.stub(:find).with("37") { mock_diploma }
      get :show, :id => "37"
      assigns(:diploma).should be(mock_diploma)
    end
  end

  describe "GET new" do
    it "assigns a new diploma as @diploma" do
      Diploma.stub(:new) { mock_diploma }
      get :new
      assigns(:diploma).should be(mock_diploma)
    end
  end

  describe "GET edit" do
    it "assigns the requested diploma as @diploma" do
      Diploma.stub(:find).with("37") { mock_diploma }
      get :edit, :id => "37"
      assigns(:diploma).should be(mock_diploma)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created diploma as @diploma" do
        Diploma.stub(:new).with({'these' => 'params'}) { mock_diploma(:save => true) }
        post :create, :diploma => {'these' => 'params'}
        assigns(:diploma).should be(mock_diploma)
      end

      it "redirects to the created diploma" do
        Diploma.stub(:new) { mock_diploma(:save => true) }
        post :create, :diploma => {}
        response.should redirect_to(diploma_url(mock_diploma))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved diploma as @diploma" do
        Diploma.stub(:new).with({'these' => 'params'}) { mock_diploma(:save => false) }
        post :create, :diploma => {'these' => 'params'}
        assigns(:diploma).should be(mock_diploma)
      end

      it "re-renders the 'new' template" do
        Diploma.stub(:new) { mock_diploma(:save => false) }
        post :create, :diploma => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested diploma" do
        Diploma.stub(:find).with("37") { mock_diploma }
        mock_diploma.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :diploma => {'these' => 'params'}
      end

      it "assigns the requested diploma as @diploma" do
        Diploma.stub(:find) { mock_diploma(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:diploma).should be(mock_diploma)
      end

      it "redirects to the diploma" do
        Diploma.stub(:find) { mock_diploma(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(diploma_url(mock_diploma))
      end
    end

    describe "with invalid params" do
      it "assigns the diploma as @diploma" do
        Diploma.stub(:find) { mock_diploma(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:diploma).should be(mock_diploma)
      end

      it "re-renders the 'edit' template" do
        Diploma.stub(:find) { mock_diploma(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested diploma" do
      Diploma.stub(:find).with("37") { mock_diploma }
      mock_diploma.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the diplomas list" do
      Diploma.stub(:find) { mock_diploma }
      delete :destroy, :id => "1"
      response.should redirect_to(diplomas_url)
    end
  end

end
